// Interactive version of the graphs generated by plotdata.py, see README.md.
// Parses the csv files maintained by do_track.sh and the commit subjects from
// commitsubjects.json (kept up to date by gitsubjects.py). Each suite has one
// graph with two views: chronological (x-axis: commit date) and commit counter
// (x-axis: commits ago, 0 = latest), the latter defaulting to the last 50
// commits. Both views can be zoomed via the slider or the mouse wheel, and the
// stats at the bottom of a graph, on the side where it overlaps fewer data
// points, always refer to the visible commits. Hovering shows a tooltip with
// the commit details, a left-click opens the commit on GitHub. The page has
// a light and a dark theme, defaulting to the browser preference.

// light and dark palettes, the dark one matching GitHub's dark mode. For
// contrast on the dark background, the blue series colors are lightened.
var THEMES = {
  light: {
    mates: "#0000ff",
    matesLabel: "#4477ff",
    bmates: "#32cd32",
    tag: "#808080",
    label: "#6e7079",
    grid: "#e8e8e8",
    axis: "#666",
    ink: "#000000",
    text: "#333333",
    tooltipBg: "#ffffff",
    tooltipBorder: "#dddddd",
    sliderBg: "#f7f7f7",
    sliderBorder: "#cccccc",
    sliderFiller: "rgba(47,69,84,0.2)",
    sliderHandle: "#ffffff",
    sliderData: "#94a3b8"
  },
  dark: {
    mates: "#58a6ff",
    matesLabel: "#79c0ff",
    bmates: "#32cd32",
    tag: "#6e7681",
    label: "#8b949e",
    grid: "#21262d",
    axis: "#6e7681",
    ink: "#c9d1d9",
    text: "#c9d1d9",
    tooltipBg: "#161b22",
    tooltipBorder: "#30363d",
    sliderBg: "#161b22",
    sliderBorder: "#30363d",
    sliderFiller: "rgba(88,166,255,0.2)",
    sliderHandle: "#c9d1d9",
    sliderData: "#7d8590"
  }
};

var COLORS = THEMES.light;

// switch the chart palette and the page theme, see renderAll for the theme
// toggle handling and the browser preference default
function setTheme(theme) {
  COLORS = THEMES[theme] || THEMES.light;
  if (typeof document !== "undefined") {
    document.documentElement.dataset.theme = theme;
  }
}

var GRID = {
  left: 64,
  rightChronological: 24,
  rightCommits: 70,
  top: 60,
  bottom: 96
};

var SF_COMMIT_URL = "https://github.com/official-stockfish/Stockfish/commit/";

var SUITES = [
  { key: "matetrack", file: "matetrack1000000.csv", label: "general mate problems (matetrack.epd)", tagPosition: "insideEndBottom" },
  { key: "classic", file: "classic1000000.csv", label: "classical endgames (classic280.epd)", tagPosition: "insideEndTop" }
];

var VIEWS = ["chronological", "commits"];

function esc(s) {
  return String(s).replace(/[&<>"']/g, function (c) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
  });
}

function parseCSV(text) {
  var rows = [];
  var lines = text.split(/\r?\n/);
  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];
    if (!line || line.indexOf("Commit") === 0) continue; // ignore the header
    var p = line.split(",");
    if (p.length < 9 || p[1].length !== 40) continue;
    var hasStats = p[2] !== "";
    rows.push({
      date: Date.parse(p[0]),
      sha: p[1],
      positions: hasStats ? +p[2] : null,
      mates: hasStats ? +p[3] : null,
      bmates: hasStats ? +p[4] : null,
      better: hasStats && p[5] ? +p[5] : 0,
      wrong: hasStats && p[6] ? +p[6] : 0,
      badpvs: hasStats && p[7] ? +p[7] : 0,
      issues: hasStats
        ? (p[5] ? +p[5] : 0) + (p[6] ? +p[6] : 0) + (p[7] ? +p[7] : 0)
        : null,
      tag: p.slice(8).join(",")
    });
  }
  return rows;
}

function nodesLabel(csvFile) {
  var m = csvFile.match(/(\d+)\.csv$/);
  var n = m ? +m[1] : 0;
  if (n && n % 1e9 === 0) return n / 1e9 + "G";
  if (n && n % 1e6 === 0) return n / 1e6 + "M";
  if (n && n % 1e3 === 0) return n / 1e3 + "K";
  return "" + n;
}

function goat(rows, key) {
  var idx = -1;
  var max = -Infinity;
  for (var i = 0; i < rows.length; i++) {
    if (rows[i][key] !== null && rows[i][key] > max) {
      max = rows[i][key];
      idx = i;
    }
  }
  return { idx: idx, value: max };
}

// stats over rows[from]..rows[to], as in plotdata.py
function statsLines(rows, from, to) {
  function line(name, key, color) {
    var vals = [];
    for (var i = from; i <= to; i++) {
      if (rows[i][key] !== null) vals.push(rows[i][key]);
    }
    if (!vals.length) return { text: "", color: color };
    var mn = Math.min.apply(null, vals);
    var mx = Math.max.apply(null, vals);
    var mean = Math.floor((mn + mx) / 2);
    var pct = (mx * 100 / Math.max(mean, 1) - 100).toFixed(1);
    return {
      text: name + " \u2282 [" + mn + ", " + mx + "] \u2248 " + mean + " \u00b1 " + pct + "%",
      color: color
    };
  }
  return [line("best mates", "bmates", COLORS.bmates), line("mates", "mates", COLORS.mates)];
}

// y-axis names for the given legend selection: the names of hidden series
// are blanked, in the chronological view only when both series are hidden
function legendAxisNames(view, selected) {
  selected = selected || {};
  if (view === "chronological") {
    return [selected.mates === false && selected["best mates"] === false ? "" : "mates"];
  }
  return [
    selected.mates === false ? "" : "mates",
    selected["best mates"] === false ? "" : "best mates"
  ];
}

// stats lines for the given legend selection: lines of hidden series are
// blanked, keeping one entry per line for the graphic elements
function legendStatsLines(lines, selected) {
  selected = selected || {};
  return lines.map(function (l, idx) {
    var key = idx === 0 ? "best mates" : "mates";
    return selected[key] === false ? { text: "", color: l.color } : l;
  });
}

// width of the stats text, using the browser text metrics, with an estimate
// as fallback for testing with node
var textWidthCtx = null;
function measureTextWidth(lines) {
  var width = 0;
  if (typeof document === "undefined") {
    for (var i = 0; i < lines.length; i++) {
      width = Math.max(width, lines[i].text.length * 6.6);
    }
    return width;
  }
  if (!textWidthCtx) {
    textWidthCtx = document.createElement("canvas").getContext("2d");
    textWidthCtx.font = "bold 11px monospace";
  }
  for (var j = 0; j < lines.length; j++) {
    width = Math.max(width, textWidthCtx.measureText(lines[j].text).width);
  }
  return width;
}

// the bottom grid side, left or right, where the stats text rectangle
// overlaps fewer data points
function statsSide(chart, rows, view, span, textWidth) {
  var gridT = GRID.top;
  var gridB = chart.getHeight() - GRID.bottom;
  var gridL = GRID.left;
  var gridR = chart.getWidth() -
    (view === "chronological" ? GRID.rightChronological : GRID.rightCommits);
  var boxTop = gridB - 44; // top of the two stats text lines, with margin
  var boxBottom = gridB - 4; // just above the grid bottom, with margin
  var counts = { left: 0, right: 0 };
  // seriesIndex 0 is always "mates", 1 is always "best mates"
  [["mates", 0], ["bmates", 1]].forEach(function (s) {
    var vTop = chart.convertFromPixel({ seriesIndex: s[1] }, [0, gridT])[1];
    var vBottom = chart.convertFromPixel({ seriesIndex: s[1] }, [0, gridB])[1];
    var xMin = chart.convertFromPixel({ seriesIndex: s[1] }, [gridL, 0])[0];
    var xMax = chart.convertFromPixel({ seriesIndex: s[1] }, [gridR, 0])[0];
    var vSpan = vTop - vBottom || 1;
    var xSpan = xMax - xMin || 1;
    for (var i = span.from; i <= span.to; i++) {
      var v = rows[i][s[0]];
      if (v === null) continue;
      var py = gridB - ((v - vBottom) / vSpan) * (gridB - gridT);
      if (py < boxTop || py > boxBottom) continue;
      var x = view === "chronological" ? rows[i].date : i - rows.length + 1;
      var px = gridL + ((x - xMin) / xSpan) * (gridR - gridL);
      if (px >= gridL + 4 && px <= gridL + 12 + textWidth) counts.left++;
      else if (px >= gridR - 12 - textWidth && px <= gridR - 4) counts.right++;
    }
  });
  return counts.left <= counts.right ? "left" : "right";
}

// stats text at the bottom inside the grid, on the given side
function statsGraphic(lines, side, rightMargin) {
  return {
    graphic: {
      elements: lines.map(function (l, idx) {
        var element = {
          type: "text",
          id: "stats-" + idx,
          silent: true,
          z: 100,
          style: { text: l.text, fill: l.color, font: "bold 11px monospace" }
        };
        if (side === "left") {
          element.left = GRID.left + 8;
        } else {
          element.right = rightMargin + 8;
        }
        element.bottom = GRID.bottom + 8 + (lines.length - 1 - idx) * 17;
        return element;
      })
    }
  };
}

function tagMarkLine(rows, xOf, position) {
  var data = [];
  for (var i = 0; i < rows.length; i++) {
    if (rows[i].tag) data.push({ xAxis: xOf(i), name: rows[i].tag });
  }
  if (!data.length) return undefined;
  return {
    symbol: "none",
    silent: true,
    lineStyle: { color: COLORS.tag, type: "dashed", width: 0.75, opacity: 0.6 },
    label: {
      show: true,
      formatter: function (p) { return p.name; },
      rotate: 90,
      fontSize: 10,
      fontWeight: "bold",
      color: COLORS.label,
      position: position
    },
    data: data
  };
}

function goatMarkPoint(rows, key, xOf) {
  var g = goat(rows, key);
  if (g.idx < 0 || xOf(g.idx) === null) return undefined;
  return {
    // thin arrow from the text down to the data point, as in plotdata.py
    symbol: "path://M0 11 L3.5 6 L0.8 6 L0.8 -11 L-0.8 -11 L-0.8 6 L-3.5 6 Z",
    symbolSize: [7, 22],
    symbolOffset: [0, -11],
    silent: true,
    itemStyle: { color: COLORS.ink },
    label: {
      formatter: "GOAT",
      position: "top",
      distance: 2,
      fontSize: 8,
      fontWeight: "bold",
      color: COLORS.ink
    },
    data: [{ coord: [xOf(g.idx), g.value], value: g.value }]
  };
}

function makeTooltip(rows, subjects) {
  return function (params) {
    var p = null;
    for (var i = 0; i < params.length; i++) {
      if (params[i].seriesName === "best mates" || params[i].seriesName === "mates") {
        p = params[i];
        break;
      }
    }
    if (!p) return "";
    var row = rows[p.dataIndex];
    if (!row) return "";
    var subject = subjects[row.sha];
    var html =
      "<b>" + new Date(row.date).toISOString().slice(0, 10) + "</b><br>" +
      '<a href="' + SF_COMMIT_URL + row.sha + '" target="_blank" rel="noopener">' +
      row.sha.slice(0, 7) + "</a>" + (subject ? " " + esc(subject) : "") +
      "<br>mates: " + (row.mates === null ? "\u2014" : row.mates) +
      " \u00b7 best mates: " + (row.bmates === null ? "\u2014" : row.bmates);
    if (row.issues) {
      html +=
        "<br>issues: " + row.issues + " (better " + row.better +
        ", wrong " + row.wrong + ", bad PVs " + row.badpvs + ")";
    }
    if (row.tag) html += "<br>release: " + esc(row.tag);
    return html;
  };
}

function buildOptions(suite, rows, subjects, view) {
  var n = rows.length;
  var isChronological = view === "chronological";
  var xOf = isChronological
    ? function (i) { return rows[i].date; }
    : function (i) { return i - n + 1; };
  var win = Math.min(50, n);
  var xAxis = {
    name: "date",
    nameLocation: "middle",
    nameGap: 26,
    nameTextStyle: { fontSize: 12, color: COLORS.label },
    axisLine: { lineStyle: { color: COLORS.axis } },
    axisLabel: { color: COLORS.label, fontSize: 12 },
    splitLine: { show: false }
  };
  var yAxis;
  var series;
  var dataZoom = [
    { type: "inside" },
    {
      type: "slider",
      height: 44,
      bottom: 10,
      left: "19%",
      right: "19%",
      backgroundColor: COLORS.sliderBg,
      borderColor: COLORS.sliderBorder,
      fillerColor: COLORS.sliderFiller,
      handleStyle: { color: COLORS.sliderHandle, borderColor: COLORS.sliderBorder },
      moveHandleStyle: { color: COLORS.sliderBorder },
      dataBackground: {
        lineStyle: { color: COLORS.sliderData },
        areaStyle: { color: COLORS.sliderData, opacity: 0.15 }
      },
      selectedDataBackground: {
        lineStyle: { color: COLORS.matesLabel },
        areaStyle: { color: COLORS.matesLabel, opacity: 0.1 }
      }
    }
  ];

  if (isChronological) {
    xAxis.type = "time";
    yAxis = {
      type: "value",
      name: "mates",
      nameLocation: "middle",
      nameRotate: 90,
      nameGap: 52,
      nameTextStyle: { fontSize: 12, color: COLORS.label },
      scale: true,
      boundaryGap: ["0%", "25%"],
      minInterval: 1,
      axisLine: { lineStyle: { color: COLORS.axis } },
      axisLabel: { color: COLORS.label, fontSize: 12 },
      splitLine: { lineStyle: { color: COLORS.grid } }
    };
    series = [
      {
        name: "mates",
        type: "scatter",
        symbolSize: 6,
        itemStyle: { color: COLORS.mates, opacity: 0.25 },
        data: rows.map(function (r) { return [r.date, r.mates]; }),
        markLine: tagMarkLine(rows, xOf, suite.tagPosition),
        markPoint: goatMarkPoint(rows, "mates", xOf)
      },
      {
        name: "best mates",
        type: "scatter",
        symbolSize: 6,
        itemStyle: { color: COLORS.bmates, opacity: 0.25 },
        data: rows.map(function (r) { return [r.date, r.bmates]; }),
        markPoint: goatMarkPoint(rows, "bmates", xOf)
      }
    ];
  } else {
    xAxis.type = "value";
    xAxis.name = "commit counter";
    xAxis.min = 1 - n;
    xAxis.max = 0;
    xAxis.minInterval = 1;
    // the commit counter is integral, so are its tick labels
    xAxis.axisLabel.formatter = function (v) { return Math.round(v); };
    dataZoom[1].labelFormatter = function (v) { return Math.round(v); };
    // mates on the left axis, as in the chronological view, best mates on
    // the alternate right axis
    yAxis = [
      {
        type: "value",
        name: "mates",
        nameLocation: "middle",
        nameRotate: 90,
        nameGap: 52,
        nameTextStyle: { color: COLORS.matesLabel, fontSize: 12 },
        scale: true,
        boundaryGap: ["0%", "25%"],
        minInterval: 1,
        axisLine: { lineStyle: { color: COLORS.axis } },
        axisLabel: { color: COLORS.matesLabel, fontSize: 12 },
        splitLine: { lineStyle: { color: COLORS.grid } }
      },
      {
        type: "value",
        name: "best mates",
        nameLocation: "middle",
        nameRotate: 90,
        nameGap: 52,
        nameTextStyle: { color: COLORS.bmates, fontSize: 12 },
        scale: true,
        boundaryGap: ["0%", "25%"],
        minInterval: 1,
        axisLine: { lineStyle: { color: COLORS.axis } },
        axisLabel: { color: COLORS.bmates, fontSize: 12 },
        splitLine: { show: false }
      }
    ];
    dataZoom.forEach(function (dz) {
      dz.startValue = 1 - win;
      dz.endValue = 0;
    });
    var lastRow = rows[n - 1];
    var issueColor = lastRow.issues ? "#ff0000" : "#ffa500";
    var issueName = lastRow.issues ? "needs investigation" : "needed investigation";
    var issueData = [];
    for (var i = 0; i < n; i++) {
      if (rows[i].issues) issueData.push([xOf(i), rows[i].mates]);
    }
    series = [
      {
        name: "mates",
        type: "line",
        yAxisIndex: 0,
        symbol: "circle",
        symbolSize: 6,
        lineStyle: { width: 0.75, opacity: 0.5 },
        itemStyle: { color: COLORS.mates, opacity: 0.6 },
        data: rows.map(function (r, i) { return [xOf(i), r.mates]; }),
        markLine: tagMarkLine(rows, xOf, suite.tagPosition),
        markPoint: goatMarkPoint(rows, "mates", xOf)
      },
      {
        name: "best mates",
        type: "line",
        yAxisIndex: 1,
        symbol: "circle",
        symbolSize: 6,
        lineStyle: { width: 1 },
        itemStyle: { color: COLORS.bmates },
        data: rows.map(function (r, i) { return [xOf(i), r.bmates]; }),
        markPoint: goatMarkPoint(rows, "bmates", xOf)
      }
    ];
    if (issueData.length) {
      // hollow symbol drawn after the data series, so the markers show the
      // underlying dot with a colored border
      series.push({
        name: issueName,
        type: "scatter",
        yAxisIndex: 0,
        symbolSize: 10,
        progressive: 0,
        itemStyle: {
          color: "rgba(0,0,0,0)",
          borderColor: issueColor,
          borderWidth: 1.5
        },
        data: issueData
      });
    }
  }

  return {
    animation: false,
    title: {
      text:
        "Mates found with " + nodesLabel(suite.file) + " nodes per position on " +
        suite.label + ".",
      left: "center",
      textStyle: { fontSize: 13, fontWeight: "bold", color: COLORS.text }
    },
    legend: {
      top: 22,
      left: "center",
      itemWidth: 12,
      itemHeight: 8,
      itemGap: 18,
      textStyle: { fontSize: 10, color: COLORS.text }
    },
    grid: {
      left: GRID.left,
      right: isChronological ? GRID.rightChronological : GRID.rightCommits,
      top: GRID.top,
      bottom: GRID.bottom,
      show: true,
      borderWidth: 1,
      borderColor: COLORS.axis
    },
    tooltip: {
      trigger: "axis",
      confine: true,
      axisPointer: { type: "line" },
      formatter: makeTooltip(rows, subjects),
      backgroundColor: COLORS.tooltipBg,
      borderColor: COLORS.tooltipBorder,
      textStyle: { color: COLORS.text },
      extraCssText: "max-width:480px;white-space:normal;word-break:break-word;"
    },
    xAxis: xAxis,
    yAxis: yAxis,
    dataZoom: dataZoom,
    series: series
  };
}

// index of the row closest to the given x value (a date, or commits ago)
function nearestRow(rows, view, xValue) {
  var n = rows.length;
  if (view === "chronological") {
    var lo = 0;
    var hi = n - 1;
    if (xValue <= rows[0].date) return 0;
    if (xValue >= rows[hi].date) return hi;
    while (lo < hi) {
      var mid = (lo + hi) >> 1;
      if (rows[mid].date < xValue) lo = mid + 1;
      else hi = mid;
    }
    // rows[lo] is the first row with date >= xValue
    if (lo > 0 && xValue - rows[lo - 1].date <= rows[lo].date - xValue) return lo - 1;
    return lo;
  }
  return Math.max(0, Math.min(n - 1, Math.round(xValue) + n - 1));
}

// data x values at the left and right grid edge of the given chart
function visibleRange(chart, view) {
  var right = view === "chronological" ? GRID.rightChronological : GRID.rightCommits;
  var dLeft = chart.convertFromPixel({ seriesIndex: 0 }, [GRID.left, 100])[0];
  var dRight = chart.convertFromPixel({ seriesIndex: 0 }, [chart.getWidth() - right, 100])[0];
  return { dMin: Math.min(dLeft, dRight), dMax: Math.max(dLeft, dRight) };
}

// rows[from]..rows[to] currently visible in the given chart
function visibleSpan(chart, rows, view) {
  var range = visibleRange(chart, view);
  var from = nearestRow(rows, view, range.dMin);
  var to = nearestRow(rows, view, range.dMax);
  return {
    from: Math.min(from, to),
    to: Math.max(from, to),
    dMin: range.dMin,
    dMax: range.dMax
  };
}

// hovering a graph shows a tooltip with the nearest commit, a left-click
// inside the grid opens that commit on GitHub in a new window
function addClickToOpen(chart, getRows, getView) {
  chart.getZr().on("click", function (e) {
    if (!chart.containPixel("grid", [e.offsetX, e.offsetY])) return;
    var xValue = chart.convertFromPixel({ seriesIndex: 0 }, [e.offsetX, e.offsetY])[0];
    var rows = getRows();
    var row = rows[nearestRow(rows, getView(), xValue)];
    if (row) window.open(SF_COMMIT_URL + row.sha, "_blank");
  });
  chart.getZr().on("mousemove", function (e) {
    chart.getZr().setCursorStyle(
      chart.containPixel("grid", [e.offsetX, e.offsetY]) ? "pointer" : "default"
    );
  });
}

if (typeof module !== "undefined" && module.exports) {
  // for testing with node, see test.js
  module.exports = {
    SUITES: SUITES,
    VIEWS: VIEWS,
    THEMES: THEMES,
    setTheme: setTheme,
    parseCSV: parseCSV,
    buildOptions: buildOptions,
    statsLines: statsLines,
    legendAxisNames: legendAxisNames,
    legendStatsLines: legendStatsLines,
    statsSide: statsSide,
    statsGraphic: statsGraphic,
    measureTextWidth: measureTextWidth,
    nodesLabel: nodesLabel,
    goat: goat,
    nearestRow: nearestRow,
    visibleSpan: visibleSpan
  };
}

if (typeof document !== "undefined") {
  var charts = [];
  window.addEventListener("resize", function () {
    charts.forEach(function (chart) { chart.resize(); });
  });

  function fetchText(url) {
    return fetch(url).then(function (r) {
      if (!r.ok) throw new Error(url + ": HTTP " + r.status);
      return r.text();
    });
  }

  // one graph with a toggle for the suite (general mate problems vs classical
  // endgame mates), one for the view (chronological vs commit counter), and
  // one for the theme (light vs dark, defaulting to the browser preference)
  function renderAll(dataBySuite, subjects) {
    var chart = echarts.init(document.getElementById("chart"));
    charts.push(chart);

    function storedChoice(key, valid) {
      try {
        var value = localStorage.getItem(key);
        return valid.indexOf(value) !== -1 ? value : null;
      } catch (e) {
        return null;
      }
    }

    function storeChoice(key, value) {
      try {
        localStorage.setItem(key, value);
      } catch (e) {}
    }

    function initialTheme() {
      var stored = storedChoice("matetrack-theme", Object.keys(THEMES));
      if (stored) return stored;
      return window.matchMedia &&
        window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
    }

    var storedSuite = storedChoice("matetrack-suite", SUITES.map(function (s) { return s.key; }));
    var state = {
      suite: SUITES.filter(function (s) { return s.key === storedSuite; })[0] || SUITES[0],
      view: storedChoice("matetrack-view", VIEWS) || "commits",
      theme: initialTheme()
    };
    var lastMatesSelected = true; // to detect mates toggles for the rings

    function rows() {
      return dataBySuite[state.suite.key];
    }

    function syncButtons() {
      SUITES.forEach(function (s) {
        document.getElementById("btn-suite-" + s.key).className = s === state.suite ? "active" : "";
      });
      VIEWS.forEach(function (v) {
        document.getElementById("btn-view-" + v).className = v === state.view ? "active" : "";
      });
      Object.keys(THEMES).forEach(function (t) {
        document.getElementById("btn-theme-" + t).className = t === state.theme ? "active" : "";
      });
    }

    function update() {
      chart.setOption(buildOptions(state.suite, rows(), subjects, state.view), { notMerge: true });
      lastMatesSelected = true; // the legend selection resets with the options
      updateStats();
    }

    // stats over the visible commits, drawn at the bottom inside the grid,
    // with the lines of legend-hidden series blanked out
    function updateStats() {
      var r = rows();
      var span = visibleSpan(chart, r, state.view);
      var selected = (chart.getOption().legend[0] || {}).selected;
      var lines = legendStatsLines(statsLines(r, span.from, span.to), selected);
      var side = statsSide(chart, r, state.view, span, measureTextWidth(lines));
      var rightMargin = state.view === "chronological"
        ? GRID.rightChronological
        : GRID.rightCommits;
      chart.setOption(statsGraphic(lines, side, rightMargin));
    }

    // hide the y-axis names of legend-hidden series
    function updateAxisNames(selected) {
      var names = legendAxisNames(state.view, selected);
      chart.setOption(
        state.view === "chronological"
          ? { yAxis: { name: names[0] } }
          : { yAxis: [{ name: names[0] }, { name: names[1] }] }
      );
    }

    SUITES.forEach(function (suite) {
      document.getElementById("btn-suite-" + suite.key).addEventListener("click", function () {
        if (state.suite !== suite) {
          state.suite = suite;
          storeChoice("matetrack-suite", suite.key);
          syncButtons();
          update();
        }
      });
    });
    VIEWS.forEach(function (view) {
      document.getElementById("btn-view-" + view).addEventListener("click", function () {
        if (state.view !== view) {
          state.view = view;
          storeChoice("matetrack-view", view);
          syncButtons();
          update();
        }
      });
    });
    Object.keys(THEMES).forEach(function (theme) {
      document.getElementById("btn-theme-" + theme).addEventListener("click", function () {
        if (state.theme !== theme) {
          state.theme = theme;
          setTheme(theme);
          storeChoice("matetrack-theme", theme);
          syncButtons();
          update();
        }
      });
    });

    // the issue rings live on the mates axis: toggle them together with the
    // mates series, so that hiding mates also hides its axis
    chart.on("legendselectchanged", function (e) {
      var selected = e.selected;
      var matesSelected = selected.mates !== false;
      if (matesSelected !== lastMatesSelected) {
        lastMatesSelected = matesSelected;
        var issueName = null;
        chart.getOption().series.forEach(function (s) {
          if (s.name && s.name.indexOf("investigation") !== -1) issueName = s.name;
        });
        if (issueName && selected[issueName] !== matesSelected) {
          chart.dispatchAction({ type: "legendToggleSelect", name: issueName });
          selected[issueName] = matesSelected;
        }
      }
      updateAxisNames(selected);
      updateStats();
    });

    // follow browser theme changes as long as there is no explicit choice
    if (window.matchMedia) {
      var mq = window.matchMedia("(prefers-color-scheme: dark)");
      var onPreferenceChange = function (e) {
        var theme = e.matches ? "dark" : "light";
        if (state.theme !== theme && !storedChoice("matetrack-theme", Object.keys(THEMES))) {
          state.theme = theme;
          setTheme(theme);
          syncButtons();
          update();
        }
      };
      if (mq.addEventListener) mq.addEventListener("change", onPreferenceChange);
      else if (mq.addListener) mq.addListener(onPreferenceChange);
    }

    addClickToOpen(chart, rows, function () { return state.view; });
    chart.on("datazoom", updateStats);
    setTheme(state.theme);
    syncButtons();
    update();
  }

  fetchText("data/commitsubjects.json")
    .then(JSON.parse)
    .catch(function (e) {
      console.warn("no commit subjects: " + e.message);
      return {};
    })
    .then(function (subjects) {
      Promise.all(
        SUITES.map(function (suite) {
          return fetchText("data/" + suite.file).then(function (text) {
            return { suite: suite, rows: parseCSV(text) };
          });
        })
      ).then(function (loaded) {
        var dataBySuite = {};
        loaded.forEach(function (l) { dataBySuite[l.suite.key] = l.rows; });
        renderAll(dataBySuite, subjects);
      }).catch(function (e) {
        document.getElementById("chart").textContent =
          "failed to load data (" + e.message + "), " +
          "the csv files are copied to web/data by the workflow or web/preview.sh";
      });
    });
}
